### ISSUE TITLE
Syntax error in RLFLexample

### ISSUE THREAD

**Issue by josephmarlin** [robotis/rlfl#1]
Sorry, don't have time to fork and fix:

  File "full_example.py", line 10, in <module>
    import RLFLExample
  File "/home/joemarlin/Downloads/robotis-rlfl-b8ee976/examples/RLFLExample.py", line 11
    print('S', end="")
                  ^
SyntaxError: invalid syntax

**Comment by robotis** [comment]
Hello. This is python3 syntax. I plan on writing examples for python2 as soon as I have the time.

**Comment by josephmarlin** [comment]
Ah, that explains it. Thanks!
